### PR TITLE
Feature/Starter Block #101

### LINKED ISSUE #101: Add starter block
Add a starter block to use as a starting point when creating new blocks.

With the following block components:
- Block title
- Block alignment
- Block background color
- Block text color
- Block text alignment
- Innerblocks (paragraph, image, and buttons to start)

### PR DESCRIPTION
**Pull request by khleomix**
Closes #101 

### Description
- Added a starter block with a RichText heading and color options to be used as a starting point when creating new blocks.
- Block has a RichText heading with alignment and text color settings and removed formatting controls (bold, link etc.)
- A background color setting was added as well.
- With Innerblocks and allowedBlocks set to `core/paragraph`, `core/image`, and `core/buttons`

### Screenshot

Screen Recording 2020-10-31 at 01 20 07 AM

### Other

- [x] Is this issue accessible? (Section 508/WCAG 2.1AA)
- [x] Does this pass CrossBrowserTesting.com? (Edge, Safari, Chrome, Firefox)
- [x] Will this pull request require [updating the wiki?](https://github.com/WebDevStudios/wds-block-starter/wiki)

### CODE REVIEW

**Comment by khleomix** [comment]
I don't have access to buddy for this project so can't check and fix whatever is failing.

**Comment by jrfoell** [comment]
There was a composer issue, but that's fixed, now it's Prettier complaining with some strange characters:

```
npm run lint:js
> wds-blocks@2.0.0 lint:js /buddy/wds-block-starter
> wp-scripts lint-js
/buddy/wds-block-starter/src/blocks/starter/edit.js
    9:9   error  Replace `⏎↹Panel,⏎↹PanelBody,⏎↹PanelRow,⏎` with `·Panel,·PanelBody,·PanelRow·` 
```

**Comment by khleomix** [comment]
> There was a composer issue, but that's fixed, now it's Prettier complaining with some strange characters:
> 
> ```
> npm run lint:js
> > wds-blocks@2.0.0 lint:js /buddy/wds-block-starter
> > wp-scripts lint-js
> /buddy/wds-block-starter/src/blocks/starter/edit.js
>     9:9   error  Replace `⏎↹Panel,⏎↹PanelBody,⏎↹PanelRow,⏎` with `·Panel,·PanelBody,·PanelRow·` 
> ```

Thanks! Will check and fix.

**Comment by khleomix** [comment]
@jrfoell Fixed the strange characters and still failing.

**Review by gregrickaby — APPROVED** [review]

**Pull request merged**
