### PR TITLE
Adding global block constants file.

### PR DESCRIPTION
**Pull request by dcooney**
### DESCRIPTION ###
Adds a constant.js that holds global constants that can be accessed by all blocks in the library. 

### SCREENSHOTS ###
Screen Shot 2020-08-26 at 4 19 55 PM

### OTHER ###
- [ ] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [ ] Does this issue pass linting? (ESLint)

### STEPS TO VERIFY ###
Include constants as required.

```
Import { PREFIX } from '../../utils/contstants';
console.log(PREFIX); // wdsblocks
```

### DOCUMENTATION ###
Will this pull request require updating the WDS Blocks [wiki](https://github.com/WebDevStudios/wds-blocks/wiki)?
Yes, it should

### CODE REVIEW

**Comment by gregrickaby** [comment]
@dcooney I fixed the spacing errors. Prettier (on Buddy) no longer barks.

**Comment by dcooney** [comment]
Thank you @gregrickaby Appears that my local prettier config is taking precedence over the project settings. Need to investigate this.

**Comment by dcooney** [comment]
@gregrickaby I like `config.js` as well. I borrowed `constants.js` name from the NextJS WP starter.

**Comment by gregrickaby** [comment]
@dcooney Cool, we're all in agreement. Can you rename the file? Then we can merge this in.

**Comment by dcooney** [comment]
@gregrickaby File renamed.

**Pull request merged**
