### PR TITLE
Feature/#64 gutenberg 3.9.0 fixes

### LINKED ISSUE #64: Add Gutenberg v. 3.5+ support
Gutenberg v. 3.5+ breaks some blocks. Needs testing and updates for all blocks.

### PR DESCRIPTION
**Pull request by jomurgel**
Closes #64

## Description
All blocks work now as expected in 3.9. A few items deprecating in 4.0, but I think all of those potential issues are already resolved as of now in WDS-Blocks.

@coreymcollins fixed issues with `withAPIData` and `withSelect` mentioned in #64 in his PR and Task #71 and #63 respectively.

### Added
- Added custom block category WDS Blocks and housed all blocks under that heading.
screenshot 2018-09-21 14 18 11

Updated
- General data validation updates.
- Cleans up some outputs.
- Version to 1.0.7
- Readme testing versions.

## OTHER
- [x] Is this issue accessible? (Section 508/WCAG 2.0AA)
- [x] Does this issue pass linting? (ESLint)

## STEPS TO VERIFY
- Activate Gutenberg, Updated to 3.9.0.
- Activate WDS-Blocks.
- Run `npm run dev` or `npm run build` and `npm run start`
- Test blocks.

### CODE REVIEW

**Comment by coreymcollins** [comment]
These changes are looking good! I like the idea of moving everything into our own category.

I'm seeing a handful of issues that I don't think are related to any changes you made, but may be issues as of a later Gutenberg update as I don't recall having seen them before.

I figure we can address them as a part of this PR since this is a more general "make it work for 3.9" PR, and this type of cleanup would make sense.

### Warning: validateDOMNesting
When expanding the options panels (Text Options, for instance, to set the font color) I receive warnings around DOM nesting as there are `h2`, `div`, and other tags nested inside of a `p` tag.

### Unsafe lifecycle method on page load
I'm not sure if this is from us, from Gutenberg, or from a dependency... but we should look into this and see if we can resolve.

This occurs for me immediately when adding a new page as well as when adding the Hero block.


### Unsafe lifecycle method on adding Recent Posts
When adding the Recent Posts block, I get a similar unsafe lifecycle warning noting an issue with `DropDown`:


### Video background not displaying properly in dashboard
When I add a video background, the video saves and displays on the frontend but it does not appear behind my block on the backend. As a note, I am NOT experiencing the issue noted in #64.


### RichTextProvider deprecation
I haven't run through out blocks to see if we're using this anywhere yet, or if this is being thrown on core blocks. But, this notice is being thrown in the console and will be worth checking out:
```
wp.editor.RichTextProvider is deprecated and will be removed from Gutenberg in 4.0.0. Please use wp.data.select( 'core/editor' ) methods instead. Note: This is a global warning, shown regardless of whether the component is used.
```

-------

I think that's everything I'm seeing at the moment! Again, I don't think any of this is a result of your work or changes but things I'm seeing that we could probably resolve in this PR as one source for a handful of fixes.

**Comment by coreymcollins** [comment]
As far as I can tell, the only place `RichTextProvider` is being used is in a core Gutenberg file and not one of our blocks/components.

**Comment by coreymcollins** [comment]
This commit should take care of the video z-indexing issues:
https://github.com/WebDevStudios/WDS-Blocks/pull/72/commits/78013af48c7ad4647ac82c61f3731096a45dab8e

**Comment by coreymcollins** [comment]
Pushed an update here to replace `componentWillReceiveProps` with `getDerivedStateFromProps` as the former is deprecated in the latest versions of React.
https://github.com/WebDevStudios/WDS-Blocks/pull/72/commits/3d1f2397573c121afb97a885e1695d1f84b2c0c6

**Comment by coreymcollins** [comment]
It looks like the other lifecyle warnings are coming from core, as reported here: https://github.com/WordPress/gutenberg/issues/7897

**Comment by coreymcollins** [comment]
@jomurgel – I can't technically make you a reviewer on this since it's your PR, but if you could check the commits I've made that'd be great! Yours are looking good on my end, so if I get the okay from you I can merge this sucker in. I think my updates above take care of the issues I had noted.

**Comment by jomurgel** [comment]
@coreymcollins forgot to make a note here. Reviewed these last night and I think as far as I can tell the z-indexing issue and DOM nesting issues. I thought those other issues were with Gutenberg specifically so no worries.

**Pull request merged**
